M48
; DRILL file {KiCad 7.0.2} date Sun May 21 15:20:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-21T15:20:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X9.8299Y-2.314
X9.8799Y-2.314
X9.9299Y-2.314
X9.9799Y-2.314
X10.0299Y-2.314
T0
M30
